import Link from "next/link";
import Image from "next/image";
import { prisma } from "@/lib/prisma";
import { ActivityFeed, type PublicActivity } from "@/components/ActivityFeed";

export default async function HomePage() {
  const [perfumes, collections, hearts, wishlists, bids] = await Promise.all([
    prisma.perfume.findMany({ where: { status: "published", owner: { profileStatus: "published" } }, select: { id: true, name: true, listingIntent: true, publishedAt: true, createdAt: true, owner: { select: { username: true } } }, orderBy: { publishedAt: "desc" }, take: 6 }),
    prisma.collection.findMany({ where: { status: "published", owner: { profileStatus: "published" } }, select: { id: true, name: true, publishedAt: true, createdAt: true, owner: { select: { username: true } } }, orderBy: { publishedAt: "desc" }, take: 4 }),
    prisma.scentHeart.findMany({ where: { user: { profileStatus: "published" }, profile: { profileStatus: "published" } }, select: { id: true, createdAt: true, user: { select: { username: true } }, profile: { select: { username: true } } }, orderBy: { createdAt: "desc" }, take: 4 }),
    prisma.wishlistItem.findMany({ where: { user: { profileStatus: "published" } }, select: { id: true, createdAt: true, user: { select: { username: true } } }, orderBy: { createdAt: "desc" }, take: 4 }),
    prisma.bid.findMany({ where: { status: { in: ["open", "accepted", "archived"] }, bidder: { profileStatus: "published" }, perfume: { owner: { profileStatus: "published" } } }, select: { id: true, createdAt: true, bidder: { select: { username: true } }, perfume: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" }, take: 4 }),
  ]);
  const activities: PublicActivity[] = [
    ...perfumes.map((perfume) => ({ id: `perfume-${perfume.id}`, actor: perfume.owner.username, action: perfume.listingIntent === "collection" ? "added to their shelf" : "listed", subject: perfume.name, href: perfume.listingIntent === "collection" ? `/u/${perfume.owner.username}` : `/p/${perfume.id}`, time: (perfume.publishedAt ?? perfume.createdAt).getTime() })),
    ...collections.map((collection) => ({ id: `collection-${collection.id}`, actor: collection.owner.username, action: "curated", subject: collection.name, href: `/u/${collection.owner.username}/c/${collection.id}`, time: (collection.publishedAt ?? collection.createdAt).getTime() })),
    ...hearts.map((heart) => ({ id: `heart-${heart.id}`, actor: heart.user.username, action: "hearted a Podium pick from", subject: `@${heart.profile.username}`, href: `/u/${heart.profile.username}`, time: heart.createdAt.getTime() })),
    ...wishlists.map((wishlist) => ({ id: `wishlist-${wishlist.id}`, actor: wishlist.user.username, action: "saved a scent to their", subject: "Wishlist", href: `/u/${wishlist.user.username}`, time: wishlist.createdAt.getTime() })),
    ...bids.map((bid) => ({ id: `bid-${bid.id}`, actor: bid.bidder.username, action: "placed a bid on", subject: bid.perfume.name, href: `/p/${bid.perfume.id}`, time: bid.createdAt.getTime() })),
  ].sort((a, b) => b.time - a.time).slice(0, 10);

  return <div className="atelier-landing"><section className="landing-hero"><Image className="landing-hero-image" src="/atelier/atelier-landing-hero-v1.png" alt="An amber fragrance bottle in a sunlit stone gallery" fill priority sizes="100vw" /><div className="landing-hero-wash" /><div className="landing-hero-copy"><p className="eyebrow text-white/75">ATELIER · PERFUME COMMUNITY</p><h1>Make room for the scents that stay with you.</h1><p>A quiet place to discover perfumes, share your shelf, and find the bottles people are ready to pass on.</p><div className="landing-actions"><Link className="landing-primary" href="/explore">Enter Atelier <span>→</span></Link><Link className="landing-secondary" href="#how-it-works">Discover more <span>↓</span></Link></div></div><p className="landing-caption">A community built around the rituals of scent.</p></section><ActivityFeed activities={activities} /><section id="how-it-works" className="landing-intro"><p className="eyebrow">A PLACE FOR YOUR SCENT STORY</p><h2>Your perfumes are more than inventory.</h2><div className="landing-pillars"><article><span>01</span><h3>Discover</h3><p>Follow notes, houses, and the personalities behind remarkable shelves.</p></article><article><span>02</span><h3>Collect</h3><p>Build a scent profile, choose your Podium, and let your favourites speak for you.</p></article><article><span>03</span><h3>Exchange</h3><p>Buy, sell, and host bids with people who know the difference a perfume can make.</p></article></div><Link className="btn" href="/explore">Explore Atelier</Link></section></div>;
}
